name: AstroJS Deployment to Pinata

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Yarn and AstroJS dependencies
        run: yarn install

      - name: Build AstroJS website
        run: yarn build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: astrojs-website
          path: dist

      - name: Enable workflow (manually)
        if: github.event_name == 'push'
        run: echo "Enabling workflow..."

      - name: Deploy AstroJS website
        uses: actions/github-script@v6
        with:
            script: |
              // Get the PINATA_TOKEN secret from the environment
              const PINATA_TOKEN = process.env.PINATA_TOKEN;

              // Get the artifact path
              const artifactPath = `${GITHUB_WORKSPACE}/artifacts/astrojs-website`;

              // Upload the artifact files to Pinata Cloud
              const pinfile = fs.readFileSync(`${artifactPath}/index.html`);

              const res = await fetch('https://api.pinata.cloud/pinning/pin', {
                method: 'POST',
                headers: {
                  Authorization: `Bearer ${PINATA_TOKEN}`,
                },
                body: pinfile,
              });

              if (res.status === 200) {
                const data = await res.json();
                console.log('Successfully pinned files to Pinata Cloud:', data);
              } else {
                console.error('Failed to pin files to Pinata Cloud:', res);
              }
        env:
          PINATA_TOKEN: ${{ secrets.PINATA_JWT_TOKEN }}

      - name: Deploy status
        uses: actions/github-script@v6
        with:
            script: |
              // Update the deploy status to success
              const url = `https://api.github.com/repos/${process.env.GITHUB_REPOSITORY}/statuses/${process.env.GITHUB_SHA}`;
              const data = {
                state: 'success',
                message: 'AstroJS website deployed successfully to Pinata Cloud.',
                context: 'deployment',
              };

              const options = {
                method: 'PUT',
                headers: {
                  Authorization: `Bearer ${process.env.GITHUB_TOKEN}`,
                },
                body: JSON.stringify(data),
              };

              const req = HttpClient().request(url, options);
              req.on('error', (err) => {
                console.error('Failed to update deploy status:', err);
              });

              req.on('response', (res) => {
                if (res.status === 200) {
                  console.log('Successfully updated deploy status.');
                } else {
                  console.error('Failed to update deploy status:', res);
                }
              });