name: AstroJS Deployment to Pinata

on:
  push:
    branches: [ main ]  # Assuming 'main' is the default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install AstroJS dependencies
        run: yarn install

      - name: Build AstroJS website
        run: yarn build

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: astrojs-website
          path: dist

      - name: Enable workflow (manually)
        if: github.event_name == 'push'
        run: echo "Enabling workflow..."

      - name: Deploy AstroJS website
        run: |
          const fs = require('fs');
          const fetch = require('node-fetch');
          const PINATA_TOKEN = process.env.PINATA_TOKEN;
          const artifactPath = 'dist';  # Update with the actual path

          // Read the file asynchronously
          fs.promises.readFile(`${artifactPath}/index.html`)
            .then(pinfile => {
              return fetch('https://api.pinata.cloud/pinning/pin', {
                method: 'POST',
                headers: {
                  Authorization: `Bearer ${PINATA_TOKEN}`,
                },
                body: pinfile,
              });
            })
            .then(res => {
              if (res.ok) {
                return res.json();
              } else {
                throw new Error(`Failed to pin files to Pinata Cloud: ${res.status}`);
              }
            })
            .then(data => {
              console.log('Successfully pinned files to Pinata Cloud:', data);
            })
            .catch(error => {
              console.error(error);
            });

        env:
          PINATA_TOKEN: ${{ secrets.PINATA_JWT_TOKEN }}

      - name: Deploy status
        run: |
          const { request } = require('@octokit/request');
          const data = {
            state: 'success',
            description: 'AstroJS website deployed successfully to Pinata Cloud.',
            context: 'deployment',
          };

          request('POST /repos/{owner}/{repo}/statuses/{sha}', {
            owner: process.env.GITHUB_REPOSITORY.split('/')[0],
            repo: process.env.GITHUB_REPOSITORY.split('/')[1],
            sha: process.env.GITHUB_SHA,
            ...data,
            headers: {
              authorization: `token ${process.env.GITHUB_TOKEN}`,
            },
          })
            .then(res => {
              if (res.status === 201) {
                console.log('Successfully updated deploy status.');
              } else {
                throw new Error(`Failed to update deploy status: ${res.status}`);
              }
            })
            .catch(error => {
              console.error(error);
            });

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
