name: AstroJS Deployment to Pinata

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Yarn and AstroJS dependencies
        run: yarn install

      - name: Build AstroJS website
        run: yarn build

      - name: Upload AstroJS files to Pinata Cloud
        uses: pinata/pinata-actions@v1
        with:
          pinata-token: ${{ secrets.PINATA_TOKEN }}
          filenames: 'dist/*'
          directory: dist
          pinata-link-type: 'Ipfs'

      - name: Set deploy status
        uses: peter-evans/create-status@v2.3.1
        with:
          state: 'pending'
          message: 'Deploying to Pinata Cloud...'
          context: 'deployment'

      - name: Deploy AstroJS website to Pinata Cloud
        run: curl -sS -H 'Authorization: Bearer ${{ secrets.PINATA_JWT_TOKEN }}' https://api.pinata.cloud/pinning/pin -X POST -F pinFile=@dist/index.html

      - name: Set deploy status
        uses: peter-evans/create-status@v2.3.1
        with:
          state: 'success'
          message: 'AstroJS website deployed successfully to Pinata Cloud.'
          context: 'deployment'